# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Очікує перевірки'),
                    ('checked', 'Перевірено'),
                ],
                default='pending',
                max_length=20,
                verbose_name='Статус',
            ),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Коментар викладача',
            ),
            preserve_default=False,
        ),
    ]
