# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_message_chat_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(blank=True, max_length=120, verbose_name='Категорія уроку'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер уроку'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/', verbose_name='Відеоурок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf_material',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/', verbose_name='PDF-матеріал'),
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
    ]
