# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_materials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва тесту')),
                ('description', models.TextField(blank=True, verbose_name='Опис тесту')),
                ('time_limit', models.PositiveIntegerField(default=10, verbose_name='Час на виконання, хв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тести',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Питання')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Номер питання')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Питання тесту',
                'verbose_name_plural': 'Питання тесту',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Правильних відповідей')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Усього питань')),
                ('percent', models.PositiveIntegerField(default=0, verbose_name='Результат, %')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Початок')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершення')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz', verbose_name='Тест')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Спроба тесту',
                'verbose_name_plural': 'Спроби тестів',
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Варіант відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна відповідь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quizquestion', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Варіант відповіді',
                'verbose_name_plural': 'Варіанти відповідей',
            },
        ),
    ]
