# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_quiz_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='option_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Варіант 1'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Варіант 2'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Варіант 3'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Варіант 4'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер правильної відповіді'),
        ),
    ]
