# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_quizquestion_inline_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показувати курс'),
        ),
    ]
