# Generated by Codex on 2026-05-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_is_visible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль для запису на курс'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва групи')),
                ('enrollment_password', models.CharField(blank=True, max_length=100, verbose_name='Пароль групи')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='courses.course', verbose_name='Курс')),
                ('students', models.ManyToManyField(blank=True, related_name='course_groups', to=settings.AUTH_USER_MODEL, verbose_name='Студенти групи')),
            ],
            options={
                'verbose_name': 'Група студентів',
                'verbose_name_plural': 'Групи студентів',
            },
        ),
    ]
