# Generated by Django 6.0.5 on 2026-05-15 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lms_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Назва тегу')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='favoritecourse',
            options={'verbose_name': 'Обраний курс', 'verbose_name_plural': 'Обрані курси'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Прогрес уроку', 'verbose_name_plural': 'Прогрес уроків'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'Відповідь студента', 'verbose_name_plural': 'Відповіді студентів'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('homework', 'Домашнє завдання'), ('practice', 'Практична робота'), ('lab', 'Лабораторна робота')], default='homework', max_length=20, verbose_name='Тип роботи'),
        ),
        migrations.AddField(
            model_name='course',
            name='co_teachers',
            field=models.ManyToManyField(blank=True, related_name='assisted_courses', to=settings.AUTH_USER_MODEL, verbose_name='Додаткові викладачі'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='lesson_presentations/', verbose_name='Презентація'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Витрачено секунд'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Опис курсу'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Студенти'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва курсу'),
        ),
        migrations.AlterField(
            model_name='favoritecourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Матеріал уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва уроку'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата відправлення'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Назва модуля')),
                ('description', models.TextField(blank=True, verbose_name='Опис модуля')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль курсу',
                'verbose_name_plural': 'Модулі курсу',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.coursemodule', verbose_name='Модуль'),
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='lesson_images/', verbose_name='Зображення')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Підпис')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Зображення уроку',
                'verbose_name_plural': 'Галерея уроку',
            },
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва матеріалу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('material_type', models.CharField(choices=[('book', 'Книга'), ('article', 'Стаття'), ('video', 'Відео'), ('link', 'Посилання'), ('file', 'Файл')], default='file', max_length=20, verbose_name='Тип матеріалу')),
                ('file', models.FileField(blank=True, null=True, upload_to='library/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Матеріал бібліотеки',
                'verbose_name_plural': 'Електронна бібліотека',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Назва заняття')),
                ('starts_at', models.DateTimeField(verbose_name='Початок')),
                ('location', models.CharField(blank=True, max_length=180, verbose_name='Місце або посилання')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Розклад занять',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Досягнення')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Бали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отримання')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='courses.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Досягнення',
                'verbose_name_plural': 'Гейміфікація',
                'unique_together': {('student', 'course', 'title')},
            },
        ),
    ]
