# Generated by Django 6.0.5 on 2026-05-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_tag_alter_assignment_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentBadge',
        ),
    ]
