# Generated by Django 6.0.5 on 2026-05-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_banners/', verbose_name='Банер уроку'),
        ),
    ]
