from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('register/', views.register),
    path('login/', views.user_login),
    path('logout/', views.user_logout),
    path('dashboard/', views.dashboard),
    path('my-progress/', views.my_progress),
    path('statistics/', views.statistics),
    path('calendar/', views.calendar_view),
    path('teacher-dashboard/', views.teacher_dashboard),
    path('teacher-dashboard/create-course/', views.teacher_create_course),
    path('teacher-dashboard/create-module/', views.teacher_create_module),
    path('teacher-dashboard/create-lesson/', views.teacher_create_lesson),
    path('teacher-dashboard/create-assignment/', views.teacher_create_assignment),
    path('teacher-dashboard/create-practice/', views.teacher_create_practice),
    path('teacher-dashboard/create-group/', views.teacher_create_group),
    path('teacher-dashboard/create-test/', views.teacher_create_test),
    path('teacher-dashboard/courses/', views.teacher_courses_page),
    path('teacher-dashboard/groups/', views.teacher_groups_page),
    path('teacher-dashboard/reviews/', views.teacher_reviews_page),
    path('teacher-dashboard/tests/', views.teacher_tests_page),
    path('teacher-dashboard/library/', views.teacher_library_page),
    path('teacher-dashboard/schedule/', views.teacher_schedule_page),
    path('teacher-dashboard/analytics/', views.teacher_analytics_page),
    path('teacher-dashboard/export-grades/', views.export_grades_csv),
    path('teacher-dashboard/import-students/', views.import_students),
    path('teacher-dashboard/report-pdf/', views.course_report_pdf),
    path('gradebook/', views.gradebook),
    path('notifications/', views.notifications),
    path('notifications/<int:notification_id>/read/', views.mark_notification_read),
    path('groups/<int:group_id>/', views.group_detail),
]
